### PR TITLE
chore: Make help

### PR DESCRIPTION
**Pull request by ckadner**
#### Motivation

_Make_ it easy to understand which `Make` targets there are and what they do.

#### Modifications

- [x] Add `help` target to Makefile which extracts `##` help-comments from the Makefile itself
- [x] Add help text for first set of most commonly used targets

#### Result

```sh
$ make help
```
```yaml
Usage:
  make <target>

Targets:
  build                 Build server release image
  help                  Display this help
  install               Install server, router, launcher, and custom kernels
  build-test-image      Build the test image.
  integration-tests     Run integration tests
  python-tests          Run Python tests

```

#### Related Issues

N/A

### CODE REVIEW

**Comment by dtrifiro** [comment]
Great addition. Another change that would be helpful is explicitly marking targets as PHONY, something like I've done in [this branch](https://github.com/dtrifiro/text-generation-inference/tree/make_help) (based on this PR).

Commit: https://github.com/dtrifiro/text-generation-inference/commit/79f2511f424568acb424e36f907796a8f90b2577

**Comment by njhill** [comment]
@ckadner want to pull in @dtrifiro's commit too before we merge this?

**Comment by ckadner** [comment]
> @ckadner want to pull in @dtrifiro's commit too before we merge this?

I could. Wasn't sure if we wanted to hold off with making changes that would possibly complicate future syncs.

**Comment by ckadner** [comment]
@joerunde -- thanks for merging in the latest changes from `main` which triggered a build failure -- it revealed something I missed in PR #38 (and #43) -- to not log in to the image registries for forked PRs -- fixed now

**Review by joerunde — APPROVED** [review]
let's get this merged!

**Pull request merged**
