### PR TITLE
Update base image, rust, python deps, rust crates

### PR DESCRIPTION
**Pull request by njhill**
Including transformers 4.39.1

Protobuf can't be updated since grpc doesn't support the latest version yet.

### CODE REVIEW

**Comment by njhill** [comment]
Latest transformers doesn't work due to what I think is a bug, have opened this PR to fix in the transformers repo: https://github.com/huggingface/transformers/pull/29821

**Comment by njhill** [comment]
I have excluded transformers for now so that we can do the other updates.

**Review by joerunde — APPROVED** [review]
Lpgtm!

**Review by maxdebayser — APPROVED** [review]
LGTM

**Pull request merged**
