### PR TITLE
chore: Add initial set of GitHub actions

### PR DESCRIPTION
**Pull request by ckadner**
Initial set of GitHub actions replicating former Travis CI workflows

FYI @njhill

### CODE REVIEW

**Comment by ckadner** [comment]
@tjohnson31415

**Comment by ckadner** [comment]
GitHub is not running the workflow since it does not exist on the main branch.

I might need to create a first pass with no-op content to merge into main so that the workflow actually gets triggered on subsequent PRs.

**Comment by ckadner** [comment]
@njhill @tjohnson31415 -- this is not a finished workflow yet, but should be okay for now to have GitHub start to run the workflow for all PR's targeting the main branch.

Once merged, I will make fixes to the workflow in subsequent PRs shortly after.

**Comment by ckadner** [comment]
@njhill -- there's a repository setting to enable workflows to run on pull requests from forks. It's disabled by default because it is a security risk, but there is an option to require approval from someone with write permissions before running a workflow.

Could you take a look at these:
- [GitHub actions permissions for your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#about-github-actions-permissions-for-your-repository)
- [Approving workflow runs from public forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
- https://github.com/IBM/text-generation-inference/settings/actions

**Review by njhill — APPROVED** [review]
Thanks @ckadner

**Comment by ckadner** [comment]
First run:
https://github.com/IBM/text-generation-inference/actions/runs/6501966098/job/17660182367

**Comment by ckadner** [comment]
Oops, https://github.com/IBM/text-generation-inference/actions/runs/6501966098/job/17660182367#step:4:2283

```
#30 175.9 ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
```

**Comment by ckadner** [comment]
Latest run, after cleaning up some unused disk space:

https://github.com/IBM/text-generation-inference/actions/runs/6502152613/job/17660695647?pr=12 🏃🏻‍♂️ 🏃🏻‍♀️ 🏃🏻

**Comment by ckadner** [comment]
PR #12 separates build and test into two separate workflows

**Pull request merged**
