### PR TITLE
Ensure TRANSFORMERS_CACHE has a default value

### PR DESCRIPTION
**Pull request by Xaenalt**
If TRANSFORMERS_CACHE is empty, it will fail to load models

### CODE REVIEW

**Comment by Jooho** [comment]
@njhill could you please review this? This change was recommended by Gaurav Kumbhat

**Comment by Xaenalt** [comment]
@njhill PTAL

**Comment by njhill** [comment]
Thanks @Xaenalt, sorry for the delay, I had been thinking about the best way to handle this in the code such that the env var doesn't need to be set at all. I think it's reasonable to require this to be set explicitly since we intentionally will never download models at runtime. So it should always point to a mounted directory.

However it shouldn't be required if the `MODEL_NAME` provided is an explicit path, we can fix that. Presumably this is the case you're interested in here?

**Comment by Xaenalt** [comment]
That's correct, if we're loading an explicit model (such as via caikit), no download should be necessary. I think if it hits a case where it needs to download something and it's not set, erroring out in that case with a message to the user makes sense, but it doesn't make sense to require it when serving a model already provided

**Comment by njhill** [comment]
@Xaenalt this has been addressed in the latest update. The env var is no longer required if you're loading from an explicit path.

**Pull request closed without merging**
